// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  about: defineAsyncComponent(() => import("./About/index.vue")),
  navigation: defineAsyncComponent(() => import("./Navigation/index.vue")),
  projects: defineAsyncComponent(() => import("./Projects/index.vue")),
  work_reference: defineAsyncComponent(
    () => import("./WorkExperience/index.vue"),
  ),
});
